# -*- conf -*-
# template taken from 
# https://github.com/jwillikers/foot-config/blob/main/foot.ini

# shell=/usr/bin/fish

#font=Ubuntu Mono:size=13
#font=Noto Sans Mono:size=13
#font=Adwaita Mono:size=13
#font=DejaVuSansMono:size=12
# System Fonts
font=Monospace:size=12
line-height=16

# Not existing in current version
# underline-thickness=1px
# gamma-correct-blending=yes


initial-window-mode=maximized
bold-text-in-bright=no

# [desktop-notifications]
# command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}command=notify-send -a ${app-id} -i ${app-id} ${title} ${body}

[scrollback]
lines=100000

[key-bindings]
# clipboard-copy=Control+c XF86Copy
# clipboard-paste=Control+v XF86Paste

[search-bindings]
# cancel=Control+g Control+Shift+c Escape

[url-bindings]
# cancel=Control+g Control+Shift+c Control+d Escape

# Ubuntu Gnome Terminal
[cursor]
blink=yes

[colors-dark]
cursor= 002b36 93c1c1
background= 250a14
foreground= eeeeec
regular0= 2e3436
bright0= 555753
regular1= cc0000
bright1= ef2929
regular2= 4eba06
bright2= 8ae234
regular3= c4a000
bright3= fce94f
regular4= 3495a4
bright4= 729fcf
regular5= 75507b
bright5= ad7fa8
regular6= 06989a
bright6= 34e2e2
regular7= d3d7cf
bright7= eeeeec

# # original Solarized Dark color scheme
# [colors]
# background= 002b36
# foreground= 839496
# regular0=   073642
# regular1=   dc322f
# regular2=   859900
# regular3=   b58900
# regular4=   268bd2
# regular5=   d33682
# regular6=   2aa198
# regular7=   eee8d5
# bright0=    002b36
# bright1=    cb4b16
# bright2=    586e75
# bright3=    657b83
# bright4=    839496
# bright5=    6c71c4
# bright6=    93a1a1
# bright7=    fdf6e3

[csd]
# Top status bar
size = 30
color= ffc4c583
